services:
  rag-chatbot:
    build: .
    container_name: rag-chatbot-vlab
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./storage:/app/storage
